### ISSUE TITLE
Launching on A2 forces user logout

### ISSUE THREAD

**Issue by bakitake** [histedlab/PumpControl#4]
Launching pump you up on rig A2 somehow logs out the user? No idea how. Video is posted on slack.

**Comment by histed** [comment]
Apparently clicking on PumpYouUp immediately causes a reboot.
I'm looking for system crash logs in : /Library/Logs/DiagnosticReports

**Comment by histed** [comment]
There are four WindowServer crash logs from ~3pm yesterday.  Is this when it happened?
![image](https://user-images.githubusercontent.com/176407/103022559-396f6500-451a-11eb-96ab-b3a12a1eab05.png)

**Comment by histed** [comment]
All the logs look like this


> Process:               WindowServer [171]
> Path:                  /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer
> Identifier:            WindowServer
> Version:               600.00 (340.54)
> Code Type:             X86-64 (Native)
> Parent Process:        launchd [1]
> Responsible:           WindowServer [171]
> User ID:               88
> 
> Date/Time:             2020-12-22 15:25:42.008 -0500
> OS Version:            Mac OS X 10.14.6 (18G95)
> Report Version:        12
> Anonymous UUID:        A00EEC1A-9996-EDF8-05E7-892F3D19CE08
> 
> Sleep/Wake UUID:       FEE9C931-226F-41A7-9882-7164D1F1E1B0
> 
> Time Awake Since Boot: 4000000 seconds
> Time Since Wake:       3100000 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Signal:    Segmentation fault: 11
> Termination Reason:    Namespace SIGNAL, Code 0xb
> Terminating Process:   exc handler [171]
> 
> VM Regions Near 0:
> --> 
>     __TEXT                 000000010b9ea000-000000010b9ec000 [    8K] r-x/rwx SM=COW  /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer
> 
> Application Specific Information:
> StartTime:2020-10-31 10:14:22
> GPU:IG
> MetalDevice for accelerator(0x4a33): 0x7f96c8e05ab8 (MTLDevice: 0x10ff79000)
> IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebuffer@2
> IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebuffer@1
> 
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   com.apple.SkyLight                  0x00007fff5d0ed485 CGXBeginSurfaceLayerUpdate + 3207
> 1   com.apple.SkyLight                  0x00007fff5d19c1a9 prepare_CoreAnimation_update_state(CGXConnection*, CGXWindowSubArray, bool, bool) + 636
> 2   com.apple.SkyLight                  0x00007fff5d197c39 CGXUpdateDisplay + 7081
> 3   com.apple.SkyLight                  0x00007fff5d195e20 update_display_callback(void*, double) + 298
> 4   com.apple.SkyLight                  0x00007fff5d1da8a1 run_timer_pass + 489
> 5   com.apple.SkyLight                  0x00007fff5d20cbd2 CGXRunOneServicesPass + 180
> 6   com.apple.SkyLight                  0x00007fff5d20dd52 server_loop + 602
> 7   com.apple.SkyLight                  0x00007fff5d20daf1 SLXServer + 1349
> 8   WindowServer                        0x000000010b9eb50d 0x10b9ea000 + 5389
> 9   libdyld.dylib                       0x00007fff63dac3d5 start + 1
> 
> Thread 1:: Dispatch queue: com.apple.VirtualDisplayListener
> 0   libsystem_kernel.dylib              0x00007fff63ee122a mach_msg_trap + 10
> 1   libsystem_kernel.dylib              0x00007fff63ee176c mach_msg + 60
> 2   libsystem_kernel.dylib              0x00007fff63ee885c mach_msg_server_once + 284
> 3   com.apple.CoreDisplay               0x00007fff37d3661e 0x7fff37d2c000 + 42526
> 4   libdispatch.dylib                   0x00007fff63d5e5f8 _dispatch_call_block_and_release + 12
> 5   libdispatch.dylib                   0x00007fff63d5f63d _dispatch_client_callout + 8
> WindowServer_2020-12-22-152549_HistedRigA2.crash (file 1 of 4)
>

**Comment by histed** [comment]
With crash at this point

> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0 com.apple.SkyLight 0x00007fff5d0ed485 CGXBeginSurfaceLayerUpdate + 3207

**Comment by histed** [comment]
Looks like it's this issue:  tkinter interaction with WindowServer

> https://stackoverflow.com/questions/57435896/tkinter-crashes-computer-after-macos-10-14-6-update

**Comment by histed** [comment]
And indeed

```
> HistedRigA2:DiagnosticReports histedmh$ sw_vers
> ProductName:	Mac OS X
> ProductVersion:	10.14.6
> BuildVersion:	18G95
```

**Comment by histed** [comment]
A1-A4 all running 10.14.6  (Which is the latest 10.14 version).  

@bakitake did you run PumpYouUp on any other machine?  Did it crash that machine?

**Comment by histed** [comment]
Possible solutions: 
- upgrade python to 3.8 everywhere for pump you up
- get all the machines on 10.15 (seems fraught but possible)

**Comment by histed** [comment]
Sigh, another Python issue.  I can fix this along with the other python upgrades.

**Comment by histed** [comment]
Ugh apparently this is an issue too?!
https://github.com/pyinstaller/pyinstaller/issues/3753

**Comment by histed** [comment]
Fixed pyinstallter issue by using git version:  (bugfix is merged to master)
````pip install git+https://github.com/pyinstaller/pyinstaller````

**Comment by histed** [comment]
Compiled on A3, tested there, it works.  Copied to test rig, synced to all 12 rigs from test rig w/ scp.  Done.

**Comment by histed** [comment]
@bakitake This should be fixed, please reopen if not.
